<?php

namespace Ydle\LogsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LogsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogsRepository extends EntityRepository
{
    /**
     * Create a query for the knppaginator
     * @return type
     */
    public function createViewLogQuery()
    {
        $query = $this->createQueryBuilder('l')
                    ->addOrderBy('l.created_at', "DESC")  
        ;
        return $query;
    }
    
    /**
     * Delete all data from the logs table
     * 
     * @return integer
     */
    public function reset()
    {
        $query = $this->getEntityManager()->createQuery('DELETE FROM YdleLogsBundle:Logs');
        return $query->execute();
    }
}
