<?php

namespace Ydle\LogsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LogsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogsRepository extends EntityRepository
{
    
    public function createViewLogQuery()
    {
        $query = $this->createQueryBuilder('l')
                    ->addOrderBy('l.created_at', "DESC")  
        ;
        return $query;
    }
}
